-- Cross-school boat sharing.
-- Run once in the Supabase SQL editor BEFORE deploying the matching app code.
-- Safe to re-run. Purely additive: nothing existing is removed, and the one
-- existing table it touches (boats) just gets one extra read policy.
--
-- How it works:
--   * The owner school generates a share code for a boat (boat_share_codes,
--     visible only to the owner school + admin, so borrowers can't re-share it).
--   * Another school enters the code -> a row in boat_shares links the boat to
--     that school, which can then see it (read-only) and book lessons on it.
--   * Because schools can't see each other's lessons (RLS), double-booking is
--     checked through security definer functions that reveal ONLY the booked
--     time slots + the booking school's name — never lesson details — plus a
--     database trigger as a hard guarantee.

-- ============================================================
-- 1) Tables
-- ============================================================
create table if not exists public.boat_share_codes (
  boat_id bigint primary key references public.boats(id) on delete cascade,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.boat_shares (
  id bigint generated by default as identity primary key,
  boat_id bigint not null references public.boats(id) on delete cascade,
  school_id integer not null references public.schools(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (boat_id, school_id)
);

alter table public.boat_share_codes enable row level security;
alter table public.boat_shares enable row level security;

-- ============================================================
-- 2) Helper functions (security definer so policies on boats and
--    boat_shares can look at each other without recursing).
-- ============================================================
create or replace function public.boat_owner_school_id(p_boat_id bigint)
returns integer language sql stable security definer set search_path = ''
as $$
  select school_id::integer from public.boats where id = p_boat_id;
$$;

create or replace function public.boat_is_shared_with(p_boat_id bigint, p_school_id integer)
returns boolean language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.boat_shares
    where boat_id = p_boat_id and school_id = p_school_id
  );
$$;

-- ============================================================
-- 3) Policies
-- ============================================================
-- A school (and its instructors/students) can READ boats shared with it.
-- Writes stay with the owner school via the existing boats policies.
drop policy if exists "shared read" on public.boats;
create policy "shared read" on public.boats for select to authenticated
  using (
    public.current_role() in ('school', 'instructor', 'student')
    and public.boat_is_shared_with(id, public.current_school_id())
  );

drop policy if exists "admin full access" on public.boat_share_codes;
create policy "admin full access" on public.boat_share_codes for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

drop policy if exists "owner manages codes" on public.boat_share_codes;
create policy "owner manages codes" on public.boat_share_codes for all to authenticated
  using (public.current_role() = 'school' and public.boat_owner_school_id(boat_id) = public.current_school_id())
  with check (public.current_role() = 'school' and public.boat_owner_school_id(boat_id) = public.current_school_id());

drop policy if exists "admin full access" on public.boat_shares;
create policy "admin full access" on public.boat_shares for all to authenticated
  using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

drop policy if exists "own links read" on public.boat_shares;
create policy "own links read" on public.boat_shares for select to authenticated
  using (public.current_role() in ('school', 'instructor') and school_id = public.current_school_id());

drop policy if exists "owner read" on public.boat_shares;
create policy "owner read" on public.boat_shares for select to authenticated
  using (public.current_role() = 'school' and public.boat_owner_school_id(boat_id) = public.current_school_id());

-- No insert policy for non-admins on purpose: links are only created through
-- link_boat_by_code() below, which checks the code.
drop policy if exists "borrower leaves" on public.boat_shares;
create policy "borrower leaves" on public.boat_shares for delete to authenticated
  using (public.current_role() = 'school' and school_id = public.current_school_id());

drop policy if exists "owner removes" on public.boat_shares;
create policy "owner removes" on public.boat_shares for delete to authenticated
  using (public.current_role() = 'school' and public.boat_owner_school_id(boat_id) = public.current_school_id());

-- ============================================================
-- 4) Linking a boat by its code
-- ============================================================
create or replace function public.link_boat_by_code(p_code text, p_school_id integer default null)
returns table (out_boat_id bigint, out_boat_name text)
language plpgsql security definer set search_path = ''
as $$
declare
  v_role text := public.current_role();
  v_target integer;
  v_boat bigint;
  v_owner integer;
begin
  if v_role = 'admin' then
    v_target := p_school_id;
  elsif v_role = 'school' then
    v_target := public.current_school_id();
  else
    raise exception 'You do not have permission to add shared boats.';
  end if;

  if v_target is null then
    raise exception 'No school selected.';
  end if;

  select c.boat_id into v_boat
  from public.boat_share_codes c
  where c.code = upper(trim(p_code));

  if v_boat is null then
    raise exception 'That boat code is not valid.';
  end if;

  select b.school_id::integer into v_owner from public.boats b where b.id = v_boat;

  if v_owner = v_target then
    raise exception 'That boat already belongs to your school.';
  end if;

  insert into public.boat_shares (boat_id, school_id)
  values (v_boat, v_target)
  on conflict do nothing;

  return query
    select b.id::bigint, b.name::text from public.boats b where b.id = v_boat;
end;
$$;

-- ============================================================
-- 5) Read helpers for the UI (schools can't read the schools table)
-- ============================================================
-- Boats shared WITH a school, plus who owns them.
create or replace function public.my_shared_boats(p_school_id integer default null)
returns table (shared_boat_id bigint, owner_school_id integer, owner_name text)
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_target integer;
begin
  if public.current_role() = 'admin' then
    v_target := p_school_id;
  else
    v_target := public.current_school_id();
  end if;

  if v_target is null then
    return;
  end if;

  return query
    select b.id::bigint, b.school_id::integer, s.name::text
    from public.boat_shares sh
    join public.boats b on b.id = sh.boat_id
    join public.schools s on s.id = b.school_id
    where sh.school_id = v_target;
end;
$$;

-- Which schools a boat-owning school has shared its boats with.
create or replace function public.boat_share_details(p_owner_school_id integer default null)
returns table (detail_boat_id bigint, detail_school_id integer, detail_school_name text)
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_role text := public.current_role();
  v_filter integer;
begin
  if v_role = 'admin' then
    v_filter := p_owner_school_id;
  elsif v_role = 'school' then
    v_filter := public.current_school_id();
    if v_filter is null then
      return;
    end if;
  else
    return;
  end if;

  return query
    select sh.boat_id::bigint, sh.school_id, s.name::text
    from public.boat_shares sh
    join public.boats b on b.id = sh.boat_id
    join public.schools s on s.id = sh.school_id
    where v_filter is null or b.school_id = v_filter;
end;
$$;

-- How many lessons other schools have booked on a boat (used to stop an owner
-- from deleting a boat that someone else still has lessons on).
create or replace function public.boat_other_school_lessons(p_boat_id bigint)
returns integer language plpgsql stable security definer set search_path = ''
as $$
declare
  v_owner integer := public.boat_owner_school_id(p_boat_id);
begin
  if not (public.current_role() = 'admin' or v_owner = public.current_school_id()) then
    return 0;
  end if;

  return (
    select count(*)::integer from public.lessons l
    where l.boat_id = p_boat_id and l.school_id is distinct from v_owner
  );
end;
$$;

-- ============================================================
-- 6) Cross-school availability check
-- ============================================================
-- Returns only the booked time slots of a boat on a day (and who booked it) —
-- no course, instructor, or student information. Only callable meaningfully by
-- the owner school, a school it's shared with, or admin.
create or replace function public.boat_booked_slots(
  p_boat_id bigint,
  p_date text,
  p_exclude_lesson_id bigint default null
)
returns table (slot_start text, slot_end text, school_name text, is_own boolean)
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_role text := public.current_role();
  v_school integer := public.current_school_id();
begin
  if v_role is null then
    return;
  end if;

  if not (
    v_role = 'admin'
    or public.boat_owner_school_id(p_boat_id) = v_school
    or public.boat_is_shared_with(p_boat_id, v_school)
  ) then
    return;
  end if;

  return query
    select
      l.start_time::text,
      l.end_time::text,
      s.name::text,
      coalesce(l.school_id = v_school, false)
    from public.lessons l
    left join public.schools s on s.id = l.school_id
    where l.boat_id = p_boat_id
      and l.date::text = p_date
      and (p_exclude_lesson_id is null or l.id <> p_exclude_lesson_id)
      and coalesce(l.status, '') <> 'Cancelled';
end;
$$;

-- ============================================================
-- 7) Hard guarantee: the database itself refuses an overlapping booking of
--    the same boat, even if two schools submit at the same moment. Edits that
--    don't touch the boat/date/time (e.g. marking a lesson Completed) are not
--    re-checked, so old data can never block normal edits.
-- ============================================================
create or replace function public.prevent_boat_double_booking()
returns trigger language plpgsql security definer set search_path = ''
as $$
begin
  if new.boat_id is null
     or new.date is null
     or new.start_time is null
     or new.end_time is null
     or coalesce(new.status, '') = 'Cancelled' then
    return new;
  end if;

  if tg_op = 'UPDATE'
     and new.boat_id is not distinct from old.boat_id
     and new.date is not distinct from old.date
     and new.start_time is not distinct from old.start_time
     and new.end_time is not distinct from old.end_time
     and coalesce(old.status, '') <> 'Cancelled' then
    return new;
  end if;

  if exists (
    select 1 from public.lessons l
    where l.boat_id = new.boat_id
      and l.date = new.date
      and l.id is distinct from new.id
      and coalesce(l.status, '') <> 'Cancelled'
      and l.start_time < new.end_time
      and new.start_time < l.end_time
  ) then
    raise exception 'This boat is already booked at that time.';
  end if;

  return new;
end;
$$;

drop trigger if exists lessons_no_boat_double_booking on public.lessons;
create trigger lessons_no_boat_double_booking
  before insert or update on public.lessons
  for each row execute function public.prevent_boat_double_booking();

-- ============================================================
-- 8) Other schools' bookings of shared boats, for the lessons board.
--    (Also available standalone in scratch-boat-sharing-board.sql.)
-- ============================================================
create or replace function public.other_school_boat_bookings(p_school_id integer default null)
returns table (
  busy_lesson_id bigint,
  busy_date text,
  busy_start text,
  busy_end text,
  busy_boat_id bigint,
  busy_boat_name text,
  busy_school_name text
)
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_role text := public.current_role();
  v_target integer;
begin
  if v_role = 'admin' then
    v_target := p_school_id;
  elsif v_role in ('school', 'instructor') then
    v_target := public.current_school_id();
  else
    return;
  end if;

  if v_target is null then
    return;
  end if;

  return query
    select
      l.id::bigint,
      l.date::text,
      l.start_time::text,
      l.end_time::text,
      b.id::bigint,
      b.name::text,
      s.name::text
    from public.lessons l
    join public.boats b on b.id = l.boat_id
    left join public.schools s on s.id = l.school_id
    where l.school_id is distinct from v_target
      and coalesce(l.status, '') <> 'Cancelled'
      and l.date::text >= to_char(current_date - 14, 'YYYY-MM-DD')
      and (
        b.school_id = v_target
        or exists (
          select 1 from public.boat_shares sh
          where sh.boat_id = b.id and sh.school_id = v_target
        )
      );
end;
$$;
